# Generated by Django 5.2.8 on 2025-11-14 19:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitViewProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.SlugField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('byline', models.CharField(help_text='One-line professional description', max_length=200)),
                ('about', models.TextField(help_text='Full prose about section')),
                ('aboutlines', models.TextField(blank=True, help_text="Bullet points like 'World-class Engineer'", null=True)),
                ('nicknames', models.TextField(help_text='Comma-separated list of nicknames')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('values', models.TextField(help_text="Core values like 'Move fast', 'Build in public'")),
                ('working_style', models.TextField(blank=True, help_text='Prose description of working style', null=True)),
                ('looking_for_opportunities', models.TextField(blank=True, help_text="e.g., ['Co-founder', 'Internship']", null=True)),
                ('looking_for_ideal_role', models.CharField(blank=True, max_length=200, null=True)),
                ('looking_for_deal_breakers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('profile_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('custom_domain', models.CharField(blank=True, help_text='Premium feature: tom.dev instead of orbitview.com/tom', max_length=255, null=True)),
                ('total_views', models.IntegerField(default=0)),
                ('total_conversations', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'orbitview_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIPersonality',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_personality', serialize=False, to='users.orbitviewprofile')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('witty', 'Witty'), ('technical', 'Technical')], default='professional', max_length=20)),
                ('formality_level', models.IntegerField(default=5, help_text='1 = very casual, 10 = very formal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('response_length', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', max_length=20)),
                ('custom_instructions', models.TextField(blank=True, help_text='Custom instructions for AI behavior', null=True)),
                ('personality_traits', models.JSONField(blank=True, help_text="e.g., ['enthusiastic', 'humble', 'direct']", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI personalities',
                'db_table': 'ai_personalities',
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='privacy', serialize=False, to='users.orbitviewprofile')),
                ('is_public', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'Private - Only followers can view'), ('unlisted', 'Unlisted - Not indexed, but link works'), ('public', 'Public - Indexed and discoverable')], default='private', max_length=20)),
                ('shareable_link_enabled', models.BooleanField(default=True)),
                ('password_protected', models.CharField(blank=True, help_text='Hashed password for extra privacy', max_length=255, null=True)),
                ('allowed_domains', models.JSONField(blank=True, help_text='Only people with emails from these domains can view', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'privacy_settings',
            },
        ),
        migrations.AddField(
            model_name='orbitviewprofile',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orbitviewprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orbitview_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(help_text='Organization that issued this', max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('award', 'Award'), ('publication', 'Publication'), ('speaking', 'Speaking Engagement'), ('certification', 'Certification'), ('competition', 'Competition')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'accomplishments',
                'ordering': ['display_order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ContextFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='context_files/')),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'context_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(blank=True, help_text='Anonymous session ID or authenticated user ID', max_length=255, null=True)),
                ('ai_tone_override', models.CharField(blank=True, choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('witty', 'Witty'), ('technical', 'Technical')], max_length=20, null=True)),
                ('ai_formality_override', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ai_response_length_override', models.CharField(blank=True, choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PopularQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('count', models.IntegerField(default=1)),
                ('first_asked', models.DateTimeField(auto_now_add=True)),
                ('last_asked', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_questions', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'popular_questions',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profile_pictures/')),
                ('url', models.URLField(help_text='CDN URL')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'profile_images',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('website', 'Personal Website'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('username', models.CharField(blank=True, help_text="e.g., '@tomsmith' for display", max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'social_links',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, help_text="e.g., ['AI/ML', 'hackathon', 'climate-tech']", null=True)),
                ('tech_stack', models.TextField(blank=True, help_text="Technologies used: ['React', 'Python', 'OpenAI']", null=True, verbose_name=models.CharField(max_length=50))),
                ('impact', models.TextField(blank=True, help_text="Quantifiable results: '500+ users', 'Won 1st place'", null=True)),
                ('display_order', models.IntegerField(default=0, help_text='For manual sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='users.orbitviewprofile')),
            ],
            options={
                'db_table': 'works',
                'ordering': ['display_order', '-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='work_images/')),
                ('url', models.URLField(help_text='CDN URL')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.work')),
            ],
            options={
                'db_table': 'work_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='users.work')),
            ],
            options={
                'db_table': 'work_links',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='orbitviewprofile',
            index=models.Index(fields=['username'], name='orbitview_p_usernam_626e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='orbitviewprofile',
            index=models.Index(fields=['is_public'], name='orbitview_p_is_publ_d5e60c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['profile', '-started_at'], name='conversatio_profile_155de6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['visitor_id'], name='conversatio_visitor_f5ed16_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='messages_convers_31a2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='popularquestion',
            index=models.Index(fields=['profile', '-count'], name='popular_que_profile_dcb442_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('profile', 'platform')},
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['profile', 'status'], name='works_profile_32e796_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['display_order'], name='works_display_e5f935_idx'),
        ),
    ]
